dist: trusty
language: java
jdk:
  - oraclejdk8

stages:
  - Build
  - Test

jobs:
  include:
  - stage: Build
    script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - stage: Test
    script: mvn test

cache:
  directories:
  - $HOME/.m2