#create a network and add our services into this network:
#so, "app" service will be able to connect to the mysql database from "db" servoce by the hostname="db":
#jdbc:mysql://db:3306/DOCKERDB

#Connection url for connection in the DatabaseView:
#  jdbc:mysql://db:3306/DOCKERDB, login=root, password=root
#App is available at: http://localhost:8080/entitybus/post
version: "3"

services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: dpb
      MYSQL_DATABASE: dpb
      MYSQL_ROOT_PASSWORD: dpb123
      MYSQL_PASSWORD: dpb123
    ports:
      - "3306:3306"